spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: third-party
  session:
    store-type: redis
  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    org.hibernate.SQL: debug

cors:
  allowed-origin: http://localhost:3000