spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: third-party
  session:
    store-type: redis
  data:
    redis:
      repositories:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/wa-db
    username: wa-user
    password: test1234
  redis:
    password: test1234

logging:
  level:
    org.hibernate.SQL: debug

cors:
  allowed-origins: http://localhost:3000, http://www.mirilibrary.xyz

server:
  servlet:
    session:
      cookie:
        secure: false