spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: third-party

logging:
  level:
    org.hibernate.SQL: debug

cors:
  allowed-origin: http://localhost:3000